= Best Practice Note for MPF Trustees
:edition: 1
:revdate: 2009-09-01
:copyright-year: 2009
:language: en
:title: Best Practice Note for MPF Trustees
:doctype: Supervision of MPF Intermediaries
:draft:
:stem:
:xrefstyle: short
:appendix-caption: Appendix
:appendix-refsig: Appendix
:section-caption: Paragraph
:section-refsig: Paragraph
:table-caption: Table
:example-caption: Figure
:mn-document-class: mpfa
:mn-output-extensions: xml,pdf,doc,html,rxl
:data-uri-image:

// http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/BPN/files/BPN_E.pdf

== Introduction
The Code of Conduct for MPF Intermediaries states that approved MPF trustees have a duty to use their best endeavours to supervise persons selling / advising on MPF schemes. The Authority regards this Note as a tool to assist trustees to supervise and monitor their MPF promoters and in turn, their intermediaries (both Corporate and Individual) in the marketing and selling of MPF schemes and products.

[[clause1]]
== Relationship between MPF trustees and promoters

[[clause1-1]]
=== {blank}

The Authority imposes a number of conditions when approving applications to become an approved MPF trustee. One of these requires trustees to take all reasonable steps to ensure that only registered MPF intermediaries induce or seek to induce another to become a participating employer or member of the Scheme. In addition, the Code of Conduct states that trustees have a duty to use their best endeavours to supervise and exercise proper control over persons selling / advising on MPF schemes. It is therefore expected that trustees would endeavour to ensure that the standards of conduct set out in the Code, are met by their intermediaries. Trustees should have the necessary tools at their disposal to facilitate this and where problems arise, the ability to take (either directly or indirectly) the appropriate remedial action. The Authority is aware that many trustees already have written undertakings from their promoters concerning the latters' intermediaries adherence to the Code of Conduct. The Authority commends this and would encourage all trustees to adopt the practice.

[[clause1-2]]
=== {blank}

The Authority sees merit in the undertaking, which may take the form of a separate document (e.g. a service level agreement) or an annex to any existing documentation, containing the following:-

[loweralpha]
. the means by which the promoter will ensure, as far as reasonably practicable,
that the MPF intermediaries selling / advising on the relevant MPF schemes comply with the Code of Conduct and any other regulatory documents issued by the Authority;

. the procedures to be adopted if a breach of the Code of Conduct comes to the promoter's attention;
. a summary of the promoter's complaint handling procedure and the mechanism for advising the relevant trustee of complaints received;
. reference to an ability for the trustee to conduct on-site inspections at the promoter's place of business, if the trustee deems this to be necessary;
. a commitment by the promoter to provide the trustee with annual written confirmation that the promoter and intermediaries appointed or engaged for the purpose of selling or advising on MPF schemes and products have complied with the Code of Conduct and any other regulatory documents issued by the Authority; and
. any other relevant material to ensure compliance with the Code.

If the existing relevant documentation does not address these issues or trustees are not sufficiently satisfied that they are adequately covered, they should seek to modify the undertaking, where feasible.

[[clause1-3]]
=== {blank}

To assist the Authority to promote best practices in this area, trustees are invited to copy these documents to the Authority within 3 months of the date of issue of this Note and whenever, in their opinion, substantial amendments are made. Commercially sensitive information may be excluded when forwarding the documents to the Authority.

[[clause2]]
== Relationship between promoters and their corporate intermediaries

[[clause2-1]]
=== {blank}

Whilst the majority of promoters engage corporate intermediaries to sell MPF
products, trustees generally have little direct contact with this Group. Therefore, as a best practice, trustees are invited to consider encouraging their promoters to obtain documentation from the promoters' corporate intermediaries covering some or all of the areas suggested in <<clause1>>. If, applicable, it would be helpful to the Authority, if trustees could indicate the existence of this documentation when submitting copies of the documents referred to in <<clause1-3>>. In addition, trustees are encouraged to satisfy themselves that, as far as practicable, promoters have sufficient due diligence processes in place to ensure that individual intermediaries working for their corporate intermediaries, are adequately supervised and monitored in terms of compliance with the Code of Conduct.

[[clause3]]
== On-going verification of the registration requirements of intermediaries

[[clause3-1]]
=== {blank}

Under the Code of Conduct, all MPF intermediaries must be fit and proper persons to remain registered with the Authority. Some promoters and corporate intermediaries rely predominately on self-declaration by the individuals concerned. Others have instituted various checking mechanisms which go beyond sole reliance on self-declaration, including, obtaining written confirmation from the relevant employer. This particular practice is encouraged. As a best practice, trustees are encouraged to satisfy themselves with the verification mechanism (i.e. the processes) adopted by their promoters / corporate intermediaries. In addition, either they, or the promoters / corporate intermediaries are encouraged to conduct random spot-checks (as far as this is practicable) to verify that these requirements have been met in respect of those individual intermediaries with whom they have a working relationship.

[[clause4]]
== On-site inspection of promoters by trustees

[[clause4-1]]
=== {blank}
The Authority notes that some trustees conduct regular on-site inspections of their promoters to ensure that adequate processes are in place which facilitate compliance with the Code of Conduct and other regulatory documentation issued by the Authority. This is encouraged.

[[clause5]]
== Complaint reporting mechanism between the MPFA, trustees and promoters

[[clause5-1]]
=== {blank}
As the lead MPF regulator, the Authority should be kept informed of all significant complaints. Chapter 4 paragraph 10.2(e) of the Code of Conduct already requires MPF corporate intermediaries to report certain complaints to the Authority, including, any misappropriation of client funds or forgery of client documents.

// TODO external references to Code of Conduct

[[clause5-2]]
=== {blank}
The Authority is aware that most, if not all trustees and promoters, already have detailed complaint handling procedures. If these do not exist, their production is very much encouraged.

[[clause5-3]]
=== {blank}
As suggested in <<clause1-2>>, trustees are encouraged to satisfy themselves that an effective reporting mechanism is in place with their promoters which ensures that all complaints lodged against intermediaries, particularly individual intermediaries with regard to their fitness and properness to be registered, cases which relate to systemic operational failures and all complaints which relate to a member sustaining or potentially sustaining a financial loss, are reported to them, as trustees. For the avoidance of doubt, this also extends to the areas referred to in the Code of Conduct and highlighted in <<clause5-1>>. Some trustees already report the details of such complaints to the Authority on a regular basis and this practice is encouraged.

[[clause5-4]]
=== {blank}
A number of trustees hold regular meetings with their promoters where necessary, (or use other means) to review progress on the handling of complaints particularly, those which remain outstanding or unresolved after a period of time. This practice is also encouraged.

[[clause6]]
== Vetting of Marketing Materials by trustees

[[clause6-1]]
=== {blank}
According to the Code of Conduct, promoters should ensure that the offering documents have been authorized by the Securities and Futures Commission (SFC) and approved by the Authority. In addition, promoters should ensure that all marketing materials have been authorized by the SFC. Some trustees also examine and confirm for example, that there is no misrepresentation, improper disclosure or misstatement of facts in the material before it is sent to the appropriate Regulator(s). This practice is encouraged.
