source "https://rubygems.org"

gem "metanorma", "~> 0.3"
gem "metanorma-cli", git: "https://github.com/riboseinc/metanorma-cli"
gem "metanorma-mpfd", git: "https://github.com/riboseinc/metanorma-mpfd"

# gem "metanorma-cli", path: "~/src/metanorma-cli"
# gem "metanorma-mpfd", path: "~/src/metanorma-mpfd"
