= Mandatory Provident Fund Schemes Ordinance (Cap. 485) (the "Ordinance") Prorating of Minimum and Maximum Levels of Relevant Income for Mandatory Contribution Purposes
:edition: 1
:revdate: 2001-01-09
:copyright-year: 2001
:docnumber: SU/CTR/2001/001
:status: Published
:language: en
:title: Mandatory Provident Fund Schemes Ordinance (Cap. 485) (the "Ordinance") Prorating of Minimum and Maximum Levels of Relevant Income for Mandatory Contribution Purposes
:doctype: circular
:data-uri-image:


== General

To: All approved trustees

Dear Sirs,

The Authority has issued two letters on 5 July 2000 and 29 July 2000 in relation to the subject matter clarifying the acceptable prorating arrangements in respect of the minimum and maximum levels of relevant income for mandatory contribution purposes. In particular, in consideration of the practical difficulties for the service providers and employers to prorate the maximum and minimum levels of relevant income precisely, the Authority has accepted the use of daily minimum and maximum levels of relevant income of $130 and $650 respectively, which are identical to those applicable to a casual employee who is a member of an industry scheme.

The Authority would like to further clarify that while the use of $130 and $650 as daily minimum and maximum levels of relevant income is acceptable to the Authority, the employers could still adopt the prorating method as provided under the Ordinance. In this regard, the Authority would like to remind you that you should accept the amount of mandatory contributions calculated by employers based on either prorating methods. In this connection, your scheme administration system and/or your procedures should be able to handle such situations. Furthermore, in consideration of the difficulty in verifying the amount of mandatory contributions calculated under the two prorating arrangements, the Authority would not object to your accepting any mandatory contributions the amount of which falls within the range defined by the respective amounts calculated based on the two prorating arrangements.

On a separate issue, in respect of employee contributions, some employers consider it administratively burdensome to prorate the relevant income of each existing relevant employee to determine the amount of mandatory contribution payable for the day of 31 December 2000, and to make a deduction from the employee's salary for the month of December accordingly. Instead, such employers propose to pay the maximum contribution amount for that day (for example, $32.5 based on the simplified contribution scale) for each employee out of the employers' own funds and remit such contributions to the approved trustee concerned together with the contributions in respect of the relevant income for the month of January. Please be advised that the Authority has no objection to such an arrangement and you may inform your clients accordingly.

Should you have any questions on the above, please feel free to contact your case officer.

Yours sincerely,

(Raymond Tam) +
Executive Director +
Services Supervision
